repos:

  # Type-Checking
  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: v1
    hooks:
      - id: upgrade-type-hints

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        additional_dependencies: [ types-all ]

  # Security
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.2
    hooks:
      - id: python-safety-dependencies-check

  # Linting
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [ --diff, --max-line-length=88 ]

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args: [ --diff, --line-length=88 ]

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.0
    hooks:
      - id: setup-cfg-fmt

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
      - id: htmlhint
      - id: markdown-toc
      - id: dockerfile_lint
        args: [ --json, --verbose, --dockerfile ]

  # Cloud Infrastructure
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.3
    hooks:
      - id: terraform_fmt
      - id: terraform_validate

  - repo: local
    hooks:
      - id: checkov
        name: checkov
        entry: checkov --directory \{\{cookiecutter.repo_name\}\}
        pass_filenames: false
        language: system
